---
# - name: Start a postgres backup
  # shell: "psql -c \"select pg_start_backup('initial_backup');\""
  # when: bucardo_master
  # sudo: Yes
  # sudo_user: "{{ postgresql_admin_user }}"

- name: Stop postgres
  service:
    name: postgresql
    state: stopped
  when: bucardo_slave

- name: Make temporary copy of files
  shell: "cp {{ postgresql_data_directory }}/{{ item }} {{ postgresql_data_directory }}/../{{ item }}"
  sudo: Yes
  sudo_user: "{{ postgresql_admin_user }}"
  when: bucardo_slave
  with_items:
    - postgresql.conf
    - recovery.conf

- name: Remove all postgres data
  file:
    path: "{{ postgresql_data_directory }}"
    state: absent
  sudo: Yes
  sudo_user: root
  when: bucardo_slave

- name: Stream existing data from master to replica
  shell: "PGPASSWORD={{ bucardo_user_pass }} pg_basebackup -h {{ bucardo_master_database_host }} -D {{ postgresql_data_directory }} -P -U {{ bucardo_user }} --xlog-method=stream --no-password"
  sudo: Yes
  sudo_user: "{{ postgresql_admin_user }}"
  when: bucardo_slave

- name: Restore temporary copy of postgresql.conf
  shell: "mv {{ postgresql_data_directory }}/../{{ item }} {{ postgresql_data_directory }}/{{ item }}"
  sudo: Yes
  sudo_user: "{{ postgresql_admin_user }}"
  when: bucardo_slave
  with_items:
    - postgresql.conf
    - recovery.conf

- name: Restart postgres
  service:
    name: postgresql
    state: restarted
  sudo: Yes

# - name: Ensure that we have permission to synchronize data
  # shell: "chmod -R 777 /data"
  # sudo: Yes
  # sudo_user: root

# - name: Synchronize postgres data between hosts
  # shell: "rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' -cva --inplace --exclude=\"*pg_xlog*,recovery.conf,*pg_stat_tmp*\" {{ postgresql_data_directory }} {{ item }}:{{ postgresql_data_directory }}"
  # with_items: bucardo_slave_database_hosts
  # when: bucardo_master

# - name: Stop the backup process
  # shell: "psql -c \"select pg_stop_backup();\""
  # when: bucardo_master
  # sudo: Yes
  # sudo_user: "{{ postgresql_admin_user }}"
