---
- name: Install Bucardo dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libdbix-safe-perl
    - libboolean-perl
    - libdbd-pg-perl
    - postgresql-plperl-9.4
    - expect

# - name: Download Bucardo
  # get_url:
    # url: http://bucardo.org/downloads/Bucardo-5.3.1.tar.gz
    # dest: /tmp/bucardo.tar.gz

# - name: Create temporary directory
  # file:
    # state: directory
    # path: /tmp/bucardo

# - name: Unarchive Bucardo
  # unarchive:
    # src: /tmp/bucardo.tar.gz
    # dest: /tmp/bucardo
    # copy: no

# - name: Build Bucardo Makefile
  # shell: "perl Makefile.PL"
  # args:
    # chdir: /tmp/bucardo/Bucardo-5.3.1/

# - name: Make Bucardo
  # shell: "make"
  # args:
    # chdir: /tmp/bucardo/Bucardo-5.3.1/

# - name: Install Bucardo
  # shell: "make install"
  # sudo: Yes
  # sudo_user: root
  # args:
    # chdir: /tmp/bucardo/Bucardo-5.3.1/

# - name: Write install script
  # copy:
    # src=install.sh
    # dest="/tmp/install_bucardo.sh"
    # owner="{{ postgresql_admin_user }}"
    # mode=0755

# - name: Create bucardo user
  # postgresql_user:
    # name: bucardo
    # role_attr_flags: SUPERUSER

# - name: Create bucardo log directory
  # file:
    # state: directory
    # path: /var/log/bucardo

# - name: Install Bucardo on the database
  # shell: "/tmp/install_bucardo.sh"
  # sudo: Yes
  # sudo_user: "{{ postgresql_admin_user }}"
